from pathlib import Path

ROOT = Path('/app/BIG_PAW_v1.0_FINAL3_domain_ready_package')

# Replace the final puppy detail page with a small, stable version.
p = ROOT / 'puppy-detail.html'
p.write_text(r'''<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>子犬詳細｜BIG PAW</title><link rel="stylesheet" href="assets/style.css"><style>body{background:#fffafb;color:#514653;margin:0}.bp{max-width:760px;margin:auto;padding:14px}.top{display:flex;align-items:center;justify-content:space-between;padding:10px 0}.logo{font-weight:900;font-size:22px;text-decoration:none;color:#514653}.gallery{display:grid;grid-template-columns:1fr 1fr;gap:8px}.gallery img{width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:16px;background:#f8e9ef}.gallery img:first-child{grid-column:1/-1;aspect-ratio:4/3}.card{background:#fff;border:1px solid #f0dbe5;border-radius:20px;padding:18px;margin:16px 0}.facts{display:grid;grid-template-columns:1fr 1fr;gap:9px}.fact{background:#fff7fa;border-radius:12px;padding:10px}.fact small{display:block;color:#8c7c88}.desc{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.75}.btn{display:block;width:100%;box-sizing:border-box;text-align:center;padding:14px;border-radius:14px;border:1px solid #ef7fa8;background:#fff;color:#ad5678;font-weight:900;text-decoration:none;margin-top:10px}.primary{background:#ef7fa8;color:#fff}.viewer{display:none;position:fixed;inset:0;background:#000e;z-index:9999;align-items:center;justify-content:center;padding:15px}.viewer.open{display:flex}.viewer img{max-width:100%;max-height:88vh;object-fit:contain}.close{position:absolute;right:16px;top:16px;font-size:30px;border:0;border-radius:50%;width:44px;height:44px}.photo-empty{aspect-ratio:4/3;border-radius:16px;background:#f8e9ef;display:grid;place-items:center;font-size:58px}</style></head><body><main class="bp"><div class="top"><a class="logo" href="/">🐾 BIG PAW</a><a href="javascript:history.back()" style="color:#8b6575">戻る</a></div><div id="app"><div class="card">読み込み中...</div></div></main><div id="viewer" class="viewer"><button class="close">×</button><img alt="子犬の写真"></div><script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>{v=(v??'').toString().trim();return(!v||v==='-'||v==='null'||v==='undefined')?'':v};
const first=(...a)=>{for(const x of a){const v=clean(x);if(v)return v}return ''};
const id=new URLSearchParams(location.search).get('id');
function photo(x){if(!x)return'';if(typeof x==='string')return clean(x);return first(x.url,x.imageUrl,x.image_url,x.path,x.src)}
async function getJson(url){const r=await fetch(url,{credentials:'same-origin'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}
function favs(){try{return JSON.parse(localStorage.getItem('bigpaw_favorites')||'[]').map(String)}catch(e){return[]}}
function saveFavs(a){a=[...new Set(a.map(String).filter(Boolean))];const v=JSON.stringify(a);try{localStorage.setItem('bigpaw_favorites',v)}catch(e){}try{sessionStorage.setItem('bigpaw_favorites',v)}catch(e){}try{document.cookie='bigpaw_favorites='+encodeURIComponent(v)+'; path=/; max-age=31536000; SameSite=Lax; Domain=.bigpaw.site'}catch(e){}return a}
async function load(){try{if(!id)throw Error('子犬が指定されていません');let p=await getJson('/api/puppies/'+encodeURIComponent(id));p=p.puppy||p.item||p;let photos=[];const add=x=>{const u=photo(x);if(u&&!photos.includes(u))photos.push(u)};add(first(p.imageUrl,p.image_url,p.image,p.mainImage,p.photo));[p.images,p.photos,p.imageUrls,p.photoUrls,p.photo_urls].forEach(a=>Array.isArray(a)&&a.forEach(add));try{let j=await getJson('/api/puppies/'+encodeURIComponent(id)+'/photos');(Array.isArray(j)?j:(j.photos||j.items||j.images||[])).forEach(add)}catch(e){}let title=[p.breed,p.color,p.gender].map(clean).filter(Boolean).join('｜')||'子犬';let desc=first(p.description,p.comment,p.note,'詳しくはブリーダーへお問い合わせください。');document.title=title+'｜BIG PAW';document.getElementById('app').innerHTML=(photos.length?'<div class="gallery">'+photos.map(u=>'<img src="'+esc(u)+'" alt="子犬の写真">').join('')+'</div>':'<div class="photo-empty">🐩</div>')+'<button id="fav" class="btn">♡ お気に入りに保存</button><section class="card"><h1>'+esc(title)+'</h1><div class="facts"><div class="fact"><small>生年月日</small><b>'+esc(first(p.birthDate,p.birth_date)||'-')+'</b></div><div class="fact"><small>性別</small><b>'+esc(first(p.gender,p.sex)||'-')+'</b></div><div class="fact"><small>毛色</small><b>'+esc(first(p.color,p.coat_color,p.coatColor)||'-')+'</b></div><div class="fact"><small>現在体重</small><b>'+esc(first(p.weight,p.currentWeight,p.current_weight)||'-')+'</b></div><div class="fact"><small>見学場所</small><b>'+esc(first(p.area,p.location,p.prefecture)||'-')+'</b></div></div></section><section class="card"><h2>この子について</h2><div class="desc">'+esc(desc)+'</div></section><section class="card"><h2>健康・検査情報</h2><p>健康診断：'+esc(first(p.healthCheck,p.health)||'実施状況はお問い合わせください')+'</p><p>遺伝子検査：'+esc(first(p.geneticTest,p.genetics)||'検査状況はお問い合わせください')+'</p></section><section class="card"><h2>ブリーダー情報</h2><p><b>'+esc(first(p.breeder,p.breederName)||'BIG PAW認定ブリーダー')+'</b></p><a class="btn primary" href="inquiry.html?puppy='+encodeURIComponent(id)+'">見学・お問い合わせ</a></section>';setup(photos)}catch(e){document.getElementById('app').innerHTML='<div class="card">'+esc(e.message||'子犬情報を読み込めませんでした')+'</div>'}}
function setup(photos){const b=document.getElementById('fav');let a=favs();const paint=()=>{const saved=a.includes(String(id));b.textContent=saved?'♥ お気に入り保存済み':'♡ お気に入りに保存';b.style.background=saved?'#fff1f7':'#fff'};b.onclick=()=>{const s=String(id),i=a.indexOf(s);if(i>=0)a.splice(i,1);else a.push(s);a=saveFavs(a);paint()};paint();const v=document.getElementById('viewer'),vi=v.querySelector('img');document.querySelectorAll('.gallery img').forEach((im,i)=>im.onclick=()=>{vi.src=photos[i];v.classList.add('open')});v.querySelector('.close').onclick=()=>v.classList.remove('open');v.onclick=e=>{if(e.target===v)v.classList.remove('open')}}
load();
</script></body></html>''', encoding='utf-8')

# Ensure favorites page can render local favorites even if the server account list is empty.
fav = ROOT / 'favorites.html'
if fav.exists():
    s = fav.read_text(encoding='utf-8', errors='replace')
    js = r'''<script id="bigpaw-local-favorites-final">
(async()=>{try{const parse=v=>{try{const a=JSON.parse(v||'[]');return Array.isArray(a)?a.map(String):[]}catch(e){return[]}};let ids=[];try{ids=ids.concat(parse(localStorage.getItem('bigpaw_favorites')))}catch(e){}try{ids=ids.concat(parse(sessionStorage.getItem('bigpaw_favorites')))}catch(e){}try{const m=document.cookie.match(/(?:^|; )bigpaw_favorites=([^;]*)/);if(m)ids=ids.concat(parse(decodeURIComponent(m[1])))}catch(e){}ids=[...new Set(ids)].filter(Boolean);if(!ids.length)return;const items=[];for(const id of ids){try{const r=await fetch('/api/puppies/'+encodeURIComponent(id),{credentials:'same-origin'});if(r.ok)items.push(await r.json())}catch(e){}}if(!items.length)return;let host=document.getElementById('bigpawLocalFavorites');if(!host){host=document.createElement('div');host.id='bigpawLocalFavorites';host.style.cssText='display:grid;gap:16px;margin:20px';(document.querySelector('main')||document.body).appendChild(host)}host.innerHTML=items.map(x=>{x=x.puppy||x.item||x;const id=String(x.id||x.puppy_id||'');const imgs=x.images||x.photos||[];const img=(Array.isArray(imgs)?imgs[0]:'')||x.imageUrl||x.image_url||x.image||'';const name=[x.breed,x.color,x.gender].filter(Boolean).join(' / ')||x.name||x.title||'子犬';return '<a href="/puppy-detail.html?id='+encodeURIComponent(id)+'" style="display:block;text-decoration:none;color:inherit;border:1px solid #ead7e1;border-radius:22px;padding:14px;background:#fff">'+(img?'<img src="'+img+'" alt="" style="width:100%;max-height:320px;object-fit:cover;border-radius:16px">':'')+'<div style="font-weight:700;font-size:20px;margin-top:10px">'+name+'</div></a>'}).join('');document.querySelectorAll('*').forEach(e=>{if(e.children.length===0&&e.textContent.trim()==='まだお気に入りはありません')e.style.display='none'})}catch(e){console.error(e)}})();
</script>'''
    if 'bigpaw-local-favorites-final' not in s:
        s = s.replace('</body>', js + '</body>')
        fav.write_text(s, encoding='utf-8')

print('BIGPAW_STABILITY_FIX_OK')
