FROM python:3.13-slim
WORKDIR /app
COPY app/ /app/
RUN ["python3", "-c", "from pathlib import Path; p=Path('/app/backend/server.py'); s=p.read_text(encoding='utf-8'); a=\"if path=='/api/puppies':\\n            u=self.require(['buyer','breeder','operator']);\"; b=\"if path=='/api/puppies':\\n            u=self.require(['breeder','operator']);\"; c=\"m=re.fullmatch(r'/api/puppies/([^/]+)',path)\\n        if m:\\n            u=self.require(['buyer','breeder','operator']);\"; d=\"m=re.fullmatch(r'/api/puppies/([^/]+)',path)\\n        if m:\\n            u=self.require(['breeder','operator']);\"; e=\"iq=re.fullmatch(r'/api/inquiries/([^/]+)',path)\\n        if iq:\\n            u=self.require(['buyer','breeder','operator']);\"; f=\"iq=re.fullmatch(r'/api/inquiries/([^/]+)',path)\\n        if iq:\\n            u=self.require(['breeder','operator']);\"; assert s.count(a)==1, ('create_guard_count',s.count(a)); assert s.count(c)==1, ('edit_guard_count',s.count(c)); assert s.count(e)==1, ('inquiry_guard_count',s.count(e)); s=s.replace(a,b,1).replace(c,d,1).replace(e,f,1); p.write_text(s,encoding='utf-8'); print('PERMISSION_GUARD_OK|puppy_create=breeder_operator|puppy_edit=breeder_operator|inquiry_update=breeder_operator',flush=True)"]
RUN ["python3", "-c", "from pathlib import Path; p=Path('/app/backend/server.py'); s=p.read_text(encoding='utf-8'); a=\"m=re.fullmatch(r'/api/puppies/([^/]+)/photos',path)\\n        if m:\\n            u=self.require(['buyer','breeder','operator'])\"; b=\"m=re.fullmatch(r'/api/puppies/([^/]+)/photos',path)\\n        if m:\\n            u=self.require(['breeder','operator'])\"; q=\"r=con.execute(\\\"SELECT p.* FROM puppies p LEFT JOIN breeders b ON b.id=p.breeder_id WHERE p.id=? AND p.review_status='approved' AND (p.breeder_id IS NULL OR b.review_status='approved') AND (p.breeder_id IS NULL OR COALESCE(b.billing_suspended,0)=0)\\\",(m.group(1),)).fetchone(); con.close()\\n            return self.send_json(public_puppy_json(r),200) if r else self.send_json({'error':'not_found'},404)\"; r=\"r=con.execute(\\\"SELECT p.* FROM puppies p LEFT JOIN breeders b ON b.id=p.breeder_id WHERE p.id=? AND p.review_status='approved' AND (p.breeder_id IS NULL OR b.review_status='approved') AND (p.breeder_id IS NULL OR COALESCE(b.billing_suspended,0)=0)\\\",(m.group(1),)).fetchone()\\n            if not r: con.close(); return self.send_json({'error':'not_found'},404)\\n            out=public_puppy_json(r); ph=con.execute('SELECT stored_name FROM uploads WHERE puppy_id=? ORDER BY created_at,id',(r['id'],)).fetchall(); out['photos']=['/uploads/'+x['stored_name'] for x in ph]; con.close(); return self.send_json(out,200)\"; assert s.count(a)==1, ('photo_guard_count',s.count(a)); assert s.count(q)==1, ('public_photo_payload_count',s.count(q)); s=s.replace(a,b,1).replace(q,r,1); p.write_text(s,encoding='utf-8'); print('PHOTO_API_SPLIT_OK|public_photos=enabled|editor_metadata=breeder_operator',flush=True)"]
RUN ["python3", "-c", "from pathlib import Path; p=Path('/app/backend/server.py'); s=p.read_text(encoding='utf-8'); a='SELECT stored_name,mime FROM uploads WHERE user_id=? AND stored_name=? AND puppy_id IS NULL'; b='SELECT * FROM uploads WHERE user_id=? AND stored_name=? AND puppy_id IS NULL'; c=\"str(up['mime'] or '').lower().startswith('image/')\"; d=\"str((up['mime_type'] if 'mime_type' in up.keys() else up['mime']) or '').lower().startswith('image/')\"; e=\"self.send_header('Content-Type',up['mime'])\"; f=\"self.send_header('Content-Type',(up['mime_type'] if 'mime_type' in up.keys() else up['mime']))\"; assert s.count(a)==1, ('proof_mime_query_count',s.count(a)); assert s.count(c)==1, ('proof_mime_check_count',s.count(c)); assert s.count(e)==1, ('proof_mime_header_count',s.count(e)); s=s.replace(a,b,1).replace(c,d,1).replace(e,f,1); p.write_text(s,encoding='utf-8'); print('BREEDER_PROOF_MIME_OK|supports=mime_type_or_mime',flush=True)"]
RUN ["python3", "-c", "from pathlib import Path; p=Path('/app/backend/server.py'); s=p.read_text(encoding='utf-8'); a=\"if u['role']=='breeder':\\n                b=con.execute('SELECT * FROM breeders WHERE user_id=?',(u['id'],)).fetchone(); breeder_id=b['id'] if b else None; breeder_name=b['kennel_name'] if b else breeder_name\\n                if b: area=b['prefecture']; area_key=AREA_KEYS.get(area,'other')\"; b=\"if u['role']=='breeder':\\n                b=con.execute('SELECT * FROM breeders WHERE user_id=?',(u['id'],)).fetchone()\\n                if not b or b['review_status']!='approved': con.close(); return self.send_json({'error':'breeder_not_approved'},403)\\n                breeder_id=b['id']; breeder_name=b['kennel_name']; area=b['prefecture']; area_key=AREA_KEYS.get(area,'other')\"; c=\"review_status='approved' if u['role']=='operator' else 'pending'\"; d=\"review_status='approved'\"; e=\"            if sets:\\n                if u['role']=='breeder' and any(k in body for k in ('desc','name','imageUrl')):\\n                    sets.extend([\\\"review_status='pending'\\\",\\\"moderation_note=''\\\",'published_at=NULL'])\\n                args.append(m.group(1)); con.execute('UPDATE puppies SET '+','.join(sets)+' WHERE id=?',args); audit(con,u['id'],'puppy_updated','puppy',m.group(1),','.join(body.keys())); con.commit()\"; f=\"            if sets:\\n                args.append(m.group(1)); con.execute('UPDATE puppies SET '+','.join(sets)+' WHERE id=?',args); audit(con,u['id'],'puppy_updated','puppy',m.group(1),','.join(body.keys())); con.commit()\"; assert s.count(a)==1, ('approved_breeder_create_block_count',s.count(a)); assert s.count(c)==1, ('listing_review_status_count',s.count(c)); assert s.count(e)==1, ('edit_reapproval_block_count',s.count(e)); s=s.replace(a,b,1).replace(c,d,1).replace(e,f,1); p.write_text(s,encoding='utf-8'); print('APPROVED_BREEDER_LISTING_OK|create=direct_public|edit=stays_public',flush=True)"]
RUN ["python3", "-c", "from pathlib import Path; p=Path('/app/backend/server.py'); s=p.read_text(encoding='utf-8'); a=\"allowed={'status':'status','price':'price','desc':'description','name':'name','imageUrl':'image_url'}\"; b=\"allowed={'status':'status','price':'price','desc':'description','name':'name','imageUrl':'image_url','breed':'breed','breedKey':'breed_key','gender':'gender','color':'color','birth':'birth','weight':'weight','adultMin':'adult_min','adultMax':'adult_max','father':'father','mother':'mother','health':'health'}\"; c=\"            for k,col in allowed.items():\\n                if k in body: sets.append(f'{col}=?'); args.append(body[k])\\n            if sets:\"; d=\"            for k,col in allowed.items():\\n                if k in body: sets.append(f'{col}=?'); args.append(body[k])\\n            if 'gender' in body: sets.append('gender_key=?'); args.append('female' if body['gender']=='女の子' else 'male')\\n            if sets:\"; assert s.count(a)==1, ('puppy_edit_allowed_map_count',s.count(a)); assert s.count(c)==1, ('puppy_edit_loop_count',s.count(c)); s=s.replace(a,b,1).replace(c,d,1); p.write_text(s,encoding='utf-8'); print('PUPPY_EDIT_FIELDS_OK|breed_gender_color_birth_weight_parents_health=enabled',flush=True)"]
RUN ["python3", "-c", "from pathlib import Path; p=Path('/app/backend/server.py'); s=p.read_text(encoding='utf-8'); a=\"        m=re.fullmatch(r'/api/puppies/([^/]+)',path)\\n        if m:\\n            u=self.require(['breeder','operator']);\\n            if not u:return\\n            body=self.json_body(); con=db(); p=con.execute('SELECT * FROM puppies WHERE id=?',(m.group(1),)).fetchone()\"; route=\"        mo=re.fullmatch(r'/api/puppies/([^/]+)/photos/order',path)\\n        if mo:\\n            u=self.require(['breeder','operator'])\\n            if not u:return\\n            body=self.json_body(); ids=body.get('ids',[])\\n            if not isinstance(ids,list) or len(ids)!=len(set(str(x) for x in ids)): return self.send_json({'error':'invalid_photo_order'},400)\\n            ids=[str(x) for x in ids]; con=db(); p=con.execute('SELECT * FROM puppies WHERE id=?',(mo.group(1),)).fetchone()\\n            if not p: con.close(); return self.send_json({'error':'not_found'},404)\\n            if u['role']=='breeder':\\n                b=con.execute('SELECT id FROM breeders WHERE user_id=?',(u['id'],)).fetchone()\\n                if not b or p['breeder_id']!=b['id']: con.close(); return self.send_json({'error':'forbidden'},403)\\n            rows=con.execute('SELECT id,stored_name FROM uploads WHERE puppy_id=?',(p['id'],)).fetchall(); byid={str(r['id']):r for r in rows}\\n            if set(ids)!=set(byid.keys()): con.close(); return self.send_json({'error':'photo_order_mismatch'},409)\\n            stamp=now()\\n            for i,uid in enumerate(ids): con.execute('UPDATE uploads SET created_at=? WHERE id=? AND puppy_id=?',(stamp+i,uid,p['id']))\\n            main=('/uploads/'+byid[ids[0]]['stored_name']) if ids else ''\\n            con.execute('UPDATE puppies SET image_url=? WHERE id=?',(main,p['id'])); audit(con,u['id'],'puppy_photos_reordered','puppy',p['id'],','.join(ids)); con.commit(); con.close(); return self.send_json({'ok':True,'imageUrl':main})\\n\"; assert s.count(a)==1, ('photo_order_insert_marker_count',s.count(a)); s=s.replace(a,route+a,1); p.write_text(s,encoding='utf-8'); print('PHOTO_ORDER_API_OK|persisted_order=created_at|first_is_main',flush=True)"]
RUN ["python3", "backend/final_patch.py"]
RUN ["python3", "backend/contract_patch.py"]
RUN ["python3", "backend/video_provider_patch.py"]
RUN ["python3", "backend/visit_contact_patch.py"]
RUN ["python3", "backend/sales_policy_patch.py"]
RUN ["python3", "backend/parent_photo_layout_patch.py"]
RUN ["python3", "backend/puppy_detail_perf_patch.py"]
RUN ["python3", "backend/profile_privacy_patch.py"]
ENV PORT=8080
EXPOSE 8080
CMD ["python3", "backend/server.py"]
