from pathlib import Path
p=Path('breeder-puppy-new.html')
s=p.read_text(encoding='utf-8')
s=s.replace('<h2 style="margin-top:22px">写真・動画</h2>','<div id="editOnly" style="display:none"><h2 style="margin-top:22px">販売設定</h2><div class="field"><label>販売状況</label><select id="status"><option>募集中</option><option>商談中</option><option>成約済み</option><option>非公開</option></select></div></div><h2 style="margin-top:22px">写真</h2>')
s=s.replace('<b>メイン写真を追加</b><span class="muted">JPG / PNG / WebP・8MBまで</span><input id="photo" type="file" accept="image/jpeg,image/png,image/webp" style="display:block;margin:14px auto 0;max-width:100%">','<b>写真を追加（最大10枚）</b><span class="muted">1枚目がメイン写真です。JPG / PNG / WebP・各8MBまで</span><input id="photo" type="file" accept="image/jpeg,image/png,image/webp" multiple style="display:block;margin:14px auto 0;max-width:100%"><div id="photoPreview" style="display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:14px"></div>')
old="async function savePuppy(e){"
insert="""const editId=new URLSearchParams(location.search).get('id');
photo.addEventListener('change',()=>{photoPreview.innerHTML=[...photo.files].slice(0,10).map((f,i)=>'<div><img src=\\\"'+URL.createObjectURL(f)+'\\\" style=\\\"width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:14px\\\"><small>'+(i===0?'メイン写真':'写真 '+(i+1))+'</small></div>').join('')});
async function initEdit(){if(!editId)return;document.querySelector('h1').textContent='子犬情報を編集';editOnly.style.display='block';const ds=await BigPawBridge.breederPuppies();const d=ds.find(x=>x.id===editId);if(!d){alert('子犬情報を読み込めませんでした');location.href='admin.html';return;}const m={breed:d.breed,gender:d.gender,color:d.color,birth:d.birth,price:d.price,weight:d.weight,adultMin:d.adultMin,adultMax:d.adultMax,father:d.father,mother:d.mother,desc:d.desc,status:d.status};Object.entries(m).forEach(([k,v])=>{const e=document.getElementById(k);if(e&&v!=null)e.value=v});health.checked=!!d.health;if(d.imageUrl)photoPreview.innerHTML='<div><img src=\\\"'+d.imageUrl+'\\\" style=\\\"width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:14px\\\"><small>現在のメイン写真</small></div>';document.querySelector('.btn-wide').textContent='変更を保存する';}
initEdit();
async function savePuppy(e){"""
s=s.replace(old,insert,1)
s=s.replace("let puppy=await BigPawBridge.addPuppy({name:color.value+'の'+gender.value,","let puppy=editId?await BigPawBridge.updatePuppy(editId,{name:color.value+'の'+gender.value,status:status.value,",1)
s=s.replace("breeder:'DOG44'});if(photo.files[0]&&BigPawBridge.isServerMode()){const up=await BigPawBridge.upload(photo.files[0],puppy.id);if(up.url){puppy=await BigPawBridge.updatePuppy(puppy.id,{imageUrl:up.url})}}","breeder:'DOG44'}):await BigPawBridge.addPuppy({name:color.value+'の'+gender.value,breed:breed.value,gender:gender.value,color:color.value,birth:birth.value,price:Number(price.value),weight:Number(weight.value),adultMin:Number(adultMin.value),adultMax:Number(adultMax.value),father:father.value,mother:mother.value,health:health.checked,desc:desc.value,area:'埼玉県',areaKey:'saitama',breeder:'DOG44'});const fs=[...photo.files].slice(0,10);for(let i=0;i<fs.length;i++){const up=await BigPawBridge.upload(fs[i],puppy.id);if(i===0&&up.url)puppy=await BigPawBridge.updatePuppy(puppy.id,{imageUrl:up.url})}",1)
s=s.replace("alert('子犬情報を保存し、掲載審査へ申請しました。承認後に一般公開されます。');","alert(editId?'変更を保存しました。':'子犬情報を掲載しました。');",1)
p.write_text(s,encoding='utf-8')